name: dscore_app
description: dscore calculator app for gymnast

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  adaptive_dialog: ^1.0.1
  app_review: ^2.1.1+1
  app_tracking_transparency: ^2.0.1
  cloud_firestore: ^1.0.5
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.1.0
  firebase_core: ^1.0.3
  firebase_messaging: ^10.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4
  flutter_slidable: ^0.6.0
  fluttertoast: ^8.0.7
  google_mobile_ads: ^0.12.1+1
  intro_slider: ^2.4.3
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.4
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any

flutter_icons:
  android: true
  ios: true
  image_path: "images/icon_image.jpg"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "images/icon_image.jpg"

flutter_native_splash:
  image: "images/splash_image.jpg"
  color: "#000000"

flutter:
  uses-material-design: true
  assets:
   - images/

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

