name: calc test

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - -main
      - develop

jobs:
  unit_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.1'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test test/calculate_score_test.dart


